Fix mongo testLatestDeps failure and filter pre-release versions
mongodb-driver-sync was pinned to 5.7.0-beta1 while core and
reactivestreams were at 5.6.4, causing NoSuchMethodError on
OperationContext.<init>. Align all mongo driver pins to 5.6.4.

Also add pre-release version filtering to resolveLatestDepVersions
so beta/alpha/rc versions don't get recorded in the pinned versions
file in the future.
Signed-off-by: Gregor Zeitlinger <gregor.zeitlinger@grafana.com>