Prevent instrumentation’s Context from applying if Muzzle fails
This can cause problems if muzzle prevents an integration from loading because the class for the new field being added may not be injected.  This results in an error:

```
Caused by: java.lang.NoClassDefFoundError: datadog/trace/bootstrap/instrumentation/context/FieldBackedProvider$ContextAccessor$org$hibernate$Session$datadog$trace$bootstrap$instrumentation$hibernate$SessionState
```