Bump org.springframework.boot:spring-boot-starter-web from 3.0.4 to 3.0.5 (#8122)
Bumps
[org.springframework.boot:spring-boot-starter-web](https://github.com/spring-projects/spring-boot)
from 3.0.4 to 3.0.5.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot:spring-boot-starter-web's
releases</a>.</em></p>
<blockquote>
<h2>v3.0.5</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>EmbeddedWebServerFactoryCustomizerAutoConfiguration should not run
when embedded web server is not configured <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34659">#34659</a></li>
<li>StandardConfigDataResource can import the same file twice if the
classpath includes '.' <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34617">#34617</a></li>
<li>Loading application.yml fails with NoSuchMethodError when using
SnakeYAML 2.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34515">#34515</a></li>
<li><code>@ConfigurationProperties</code> no longer works on a mutable
Kotlin data classes <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34500">#34500</a></li>
<li>Image builds with podman fail when image buildpacks are configured
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34495">#34495</a></li>
<li>Use of <code>@EntityScan</code> causes AOT instance supplier code
generation error <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34371">#34371</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Document support for Java 20 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34726">#34726</a></li>
<li>Clarify conventions for custom error pages in WebFlux <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34705">#34705</a></li>
<li>Add documentation tip showing how to configure publishRegistry Maven
properties from the command line <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34704">#34704</a></li>
<li>Typo in Batch documentation: content instead of context <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/34646">#34646</a></li>
<li>Update two references to old APIs <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34602">#34602</a></li>
<li>Fix Javadoc in JobLauncherApplicationRunner <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/34596">#34596</a></li>
<li>Document how to get socket location for image building configuration
with podman <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34475">#34475</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Caffeine 3.1.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34662">#34662</a></li>
<li>Upgrade to Couchbase Client 3.4.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34663">#34663</a></li>
<li>Upgrade to Dropwizard Metrics 4.2.18 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34664">#34664</a></li>
<li>Upgrade to GraphQL Java 19.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34718">#34718</a></li>
<li>Upgrade to Groovy 4.0.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34665">#34665</a></li>
<li>Upgrade to Infinispan 14.0.7.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34666">#34666</a></li>
<li>Upgrade to Jedis 4.3.2 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34698">#34698</a></li>
<li>Upgrade to Jetty Reactive HTTPClient 3.0.8 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34667">#34667</a></li>
<li>Upgrade to jOOQ 3.17.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34699">#34699</a></li>
<li>Upgrade to Json-smart 2.4.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34669">#34669</a></li>
<li>Upgrade to Logback 1.4.6 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34670">#34670</a></li>
<li>Upgrade to Micrometer 1.10.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34536">#34536</a></li>
<li>Upgrade to Micrometer Tracing 1.0.3 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34537">#34537</a></li>
<li>Upgrade to Netty 4.1.90.Final <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34671">#34671</a></li>
<li>Upgrade to Reactor Bom 2022.0.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34538">#34538</a></li>
<li>Upgrade to SLF4J 2.0.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34672">#34672</a></li>
<li>Upgrade to Spring AMQP 3.0.3 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34608">#34608</a></li>
<li>Upgrade to Spring Data Bom 2022.0.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34539">#34539</a></li>
<li>Upgrade to Spring Framework 6.0.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34540">#34540</a></li>
<li>Upgrade to Spring GraphQL 1.1.3 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34541">#34541</a></li>
<li>Upgrade to Spring HATEOAS 2.0.3 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34673">#34673</a></li>
<li>Upgrade to Spring Integration 6.0.4 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34542">#34542</a></li>
<li>Upgrade to Spring Kafka 3.0.5 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34543">#34543</a></li>
<li>Upgrade to Spring Retry 2.0.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34544">#34544</a></li>
<li>Upgrade to Spring Session 3.0.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34545">#34545</a></li>
<li>Upgrade to Tomcat 10.1.7 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34674">#34674</a></li>
<li>Upgrade to UnboundID LDAPSDK 6.0.8 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/34675">#34675</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/8af13ef22cc9dd42a01823c4b716920002755c40"><code>8af13ef</code></a>
Release v3.0.5</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/fa63f6cc9ecf4d7965605b06f25cec0e348ca6e8"><code>fa63f6c</code></a>
Stop using an instance supplier in EntityScanPackages' bean
definition</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/5e08ee64832708d432e65fb6eb9d4875a76269d9"><code>5e08ee6</code></a>
Merge branch '2.7.x' into 3.0.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/69087badab8cff87dc8bbb0bf60d743ae6117e4b"><code>69087ba</code></a>
Next development version (v2.7.11-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/26376ffcb1974da8c8a18ccafba5338490673471"><code>26376ff</code></a>
Merge branch '2.7.x' into 3.0.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/1fc3c34fa294d643ad5a4ca3e58cdbb032838a25"><code>1fc3c34</code></a>
Document support for Java 20</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/14d12da5a446e641dd7450bfd956eeb621808a2a"><code>14d12da</code></a>
Upgrade to Spring Integration 6.0.4</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/82c0ba9ef847a2acf67a3e609fabfd180b7c175e"><code>82c0ba9</code></a>
Merge branch '2.7.x' into 3.0.x</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/1508e3cec81ad1f3edc630b8b3a0e607c2c3a563"><code>1508e3c</code></a>
Upgrade to Spring Integration 5.5.17</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/c56b190b6c19df5cfd11278b5386ddad84fd5e8f"><code>c56b190</code></a>
Upgrade to GraphQL Java 19.4</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.0.4...v3.0.5">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-starter-web&package-manager=gradle&previous-version=3.0.4&new-version=3.0.5)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>